[profile.default]
ffi = true
solc_version = "0.8.26"
evm_version = "cancun"
libs = ["node_modules", "lib"]
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"