# If verification fails, please check these:
# https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description
# https://github.com/foundry-rs/foundry/issues/4060
# https://github.com/foundry-rs/foundry/issues/6780

[profile.default]
ffi = true
solc_version = "0.8.26"
evm_version = "cancun"
libs = ["node_modules", "lib"]
via_ir = true
bytecode_hash = "none"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"